###  CAMINATAS CLÁSICAS

Vamos a usar la funcion $rand()$ para generar un valor aleatorio en el intevalo $[0,1]$

Vamos primero a crear una función que nos describa al caminante y dad una cantidad digamos "n" de lanzamientos de volado. 

Como primera aproximación escribimos la función "volado" para describir un vector que nos de n lanzamientos de volado, denotando por ejemplo con -1 a sol y 1 como águila.

In [1]:
function volado(n)
    rand(-1:2:1,n)
end

volado (generic function with 1 method)

Por ejemplo para 10 volados:

In [2]:
volado(10)

10-element Array{Int64,1}:
  1
  1
  1
 -1
  1
 -1
 -1
 -1
  1
 -1

observamos que nos da seis veces sol y cuatro águila

Con lo anterior debemos ser capaces de escribir un algoritmo que nos diga cual es la posición final de un caminante después de lanzar n veces la moneda. 

Y lo hacemos con la siguiente rutina: 

In [3]:
function posicion_final(n) #construimos la función que le pide al usuario el número de volados. 
    b=volado(n)#usamos la función volado para crear el vector b que tiene como componentes los valores: 1 y -1
    p=0 #vamos a partir del punto cero en la  recta númerica 
    for i in 1:n #ahora lo que haremos es sumar las entradas del vector b i.e. sumar 1 y -1 para decirle al caminante si va a la derecha o izquierda respectivamente. 
    p=b[i]+p
end
return p #imprimimos el valor p que corresponde a la posición final del caminante después de los n pasos. 
end

posicion_final (generic function with 1 method)

In [4]:
posicion_final(1) #comprobamos nuestra rutina primero con un volado pues solo tendremos 2 valores posibles para la localización final del caminante, i.e. 1 o menos 1 

1

In [5]:
posicion_final(10) #en este caso el codigo se lee como: después de lanzar diez veces la moneda, el caminante queda en la posición -2 en la recta.

0

Ahora nuestra meta es encontrar la posición final para un número k de caminantes. 

Pondremos dentro de un ciclo for nuestra rutina anterior y guardaremos las distancias finales en una lista para después hacer el histograma. 

In [6]:
function fin(n,k) #le pedimos al usuario tanto el número de volados "n" y el de caminantes "k"
    listf=zeros(k) #construimos una lista con k entradas con ceros 
    for i in 1:k #este ciclo for se usa para encontrar la distancia final de los k caminantes haciendo uso de la función de posicion_final
        d=posicion_final(n)
        listf[i]=d  #se llena la lista con las posiciones finales 
        end 
    return listf
    end 
        
    

fin (generic function with 1 method)

In [7]:
fin(10,100) #ejemplo de la función fin para 10 volados y cien caminantes

100-element Array{Float64,1}:
 -2.0
 -2.0
 -2.0
  0.0
 -2.0
 -2.0
  0.0
 -4.0
  2.0
 -2.0
 -2.0
  0.0
  2.0
  ⋮  
 -2.0
  0.0
 -4.0
  0.0
  2.0
  2.0
  8.0
  4.0
 -2.0
 -4.0
  0.0
 -8.0

Haremos el histograma 

In [8]:
fin(1,100) #cuando solo hacemos 1 volado para caminante solo nos salen unos y menos uno como un esperaría

100-element Array{Float64,1}:
 -1.0
 -1.0
  1.0
  1.0
  1.0
 -1.0
 -1.0
  1.0
 -1.0
  1.0
 -1.0
  1.0
 -1.0
  ⋮  
  1.0
 -1.0
 -1.0
 -1.0
 -1.0
  1.0
 -1.0
 -1.0
 -1.0
 -1.0
  1.0
 -1.0

In [9]:
Pkg.add("Plots")

INFO: Initializing package repository /home/juser/.julia/v0.5
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl


LoadError: GitError(Code:ERROR, Class:OS, Could not open '/home/juser/.julia/v0.5/tmpk7hZpc/METADATA/Xpress/versions/0.0.2/requires' for writing: No space left on device)

In [10]:
using Plots 


LoadError: ArgumentError: Module Plots not found in current path.
Run `Pkg.add("Plots")` to install the Plots package.